-- Database Schema for Launchpad Revenue Tracking System
-- Run this SQL in your Supabase SQL Editor

-- =====================================================
-- 1. LAUNCHPAD INVESTMENTS TABLE
-- =====================================================
-- Tracks all user investments in launchpad projects

CREATE TABLE IF NOT EXISTS launchpad_investments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES launchpad_projects(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  wallet_address TEXT NOT NULL,

  -- Investment details
  amount_usd DECIMAL(20, 2) NOT NULL,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('ETH', 'USDC')),
  token_amount DECIMAL(20, 8) NOT NULL,

  -- Blockchain data
  transaction_hash TEXT,
  block_number BIGINT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Indexes for performance
  CONSTRAINT unique_transaction UNIQUE (transaction_hash)
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_investments_project ON launchpad_investments(project_id);
CREATE INDEX IF NOT EXISTS idx_investments_wallet ON launchpad_investments(wallet_address);
CREATE INDEX IF NOT EXISTS idx_investments_user ON launchpad_investments(user_id);
CREATE INDEX IF NOT EXISTS idx_investments_status ON launchpad_investments(status);

-- Add RLS policies
ALTER TABLE launchpad_investments ENABLE ROW LEVEL SECURITY;

-- Users can view their own investments
CREATE POLICY "Users can view their own investments" ON launchpad_investments
  FOR SELECT
  USING (
    auth.uid() = user_id
    OR wallet_address = LOWER((SELECT raw_user_meta_data->>'wallet_address' FROM auth.users WHERE id = auth.uid()))
  );

-- Anyone can insert new investments
CREATE POLICY "Anyone can create investments" ON launchpad_investments
  FOR INSERT
  WITH CHECK (true);

-- Users can update their own investments
CREATE POLICY "Users can update their own investments" ON launchpad_investments
  FOR UPDATE
  USING (
    auth.uid() = user_id
    OR wallet_address = LOWER((SELECT raw_user_meta_data->>'wallet_address' FROM auth.users WHERE id = auth.uid()))
  );

-- =====================================================
-- 2. LAUNCHPAD REVENUES TABLE
-- =====================================================
-- Tracks revenue distributions to investors

CREATE TABLE IF NOT EXISTS launchpad_revenues (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES launchpad_projects(id) ON DELETE CASCADE,
  investor_address TEXT NOT NULL,

  -- Revenue details
  amount_usd DECIMAL(20, 8) NOT NULL,
  amount_eth DECIMAL(20, 18),
  amount_usdc DECIMAL(20, 6),
  distribution_currency TEXT NOT NULL CHECK (distribution_currency IN ('ETH', 'USDC')),

  -- Distribution metadata
  total_project_revenue DECIMAL(20, 2) NOT NULL, -- Total revenue generated by project
  investor_token_amount DECIMAL(20, 8) NOT NULL, -- Investor's token amount
  ownership_percentage DECIMAL(10, 6) NOT NULL, -- Percentage of total supply

  -- Blockchain data
  transaction_hash TEXT,
  block_number BIGINT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  distributed_at TIMESTAMPTZ,

  CONSTRAINT unique_revenue_transaction UNIQUE (transaction_hash)
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_revenues_project ON launchpad_revenues(project_id);
CREATE INDEX IF NOT EXISTS idx_revenues_investor ON launchpad_revenues(investor_address);
CREATE INDEX IF NOT EXISTS idx_revenues_created ON launchpad_revenues(created_at DESC);

-- Add RLS policies
ALTER TABLE launchpad_revenues ENABLE ROW LEVEL SECURITY;

-- Users can view their own revenue
CREATE POLICY "Users can view their own revenue" ON launchpad_revenues
  FOR SELECT
  USING (
    investor_address = LOWER((SELECT raw_user_meta_data->>'wallet_address' FROM auth.users WHERE id = auth.uid()))
  );

-- Only service role can insert revenues (for automated distributions)
CREATE POLICY "Service role can insert revenues" ON launchpad_revenues
  FOR INSERT
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- =====================================================
-- 3. UPDATE LAUNCHPAD_PROJECTS TABLE
-- =====================================================
-- Add fields for revenue tracking to existing launchpad_projects table

ALTER TABLE launchpad_projects
ADD COLUMN IF NOT EXISTS owner_wallet TEXT,
ADD COLUMN IF NOT EXISTS total_revenue DECIMAL(20, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_revenue_distribution TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS revenue_distribution_frequency TEXT DEFAULT 'monthly'
  CHECK (revenue_distribution_frequency IN ('daily', 'weekly', 'monthly', 'quarterly'));

-- Add index
CREATE INDEX IF NOT EXISTS idx_projects_owner_wallet ON launchpad_projects(owner_wallet);

-- =====================================================
-- 4. PROJECT REVENUE POOL TABLE
-- =====================================================
-- Tracks incoming revenue to project owner wallet

CREATE TABLE IF NOT EXISTS project_revenue_pool (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES launchpad_projects(id) ON DELETE CASCADE,

  -- Revenue details
  amount_usd DECIMAL(20, 2) NOT NULL,
  currency TEXT NOT NULL CHECK (currency IN ('ETH', 'USDC')),
  source TEXT, -- Description of revenue source

  -- Blockchain data
  transaction_hash TEXT NOT NULL,
  block_number BIGINT,
  from_address TEXT,

  -- Distribution tracking
  distributed BOOLEAN DEFAULT FALSE,
  distributed_at TIMESTAMPTZ,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT unique_pool_transaction UNIQUE (transaction_hash)
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_pool_project ON project_revenue_pool(project_id);
CREATE INDEX IF NOT EXISTS idx_pool_distributed ON project_revenue_pool(distributed);

-- Add RLS policies
ALTER TABLE project_revenue_pool ENABLE ROW LEVEL SECURITY;

-- Anyone can view revenue pool
CREATE POLICY "Anyone can view revenue pool" ON project_revenue_pool
  FOR SELECT
  USING (true);

-- Only service role can insert/update revenue pool
CREATE POLICY "Service role can manage revenue pool" ON project_revenue_pool
  FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

-- =====================================================
-- 5. INVESTOR PORTFOLIO VIEW
-- =====================================================
-- Materialized view for quick investor portfolio lookups

CREATE OR REPLACE VIEW investor_portfolio AS
SELECT
  i.wallet_address,
  i.project_id,
  p.name as project_name,
  p.token_symbol,
  SUM(i.amount_usd) as total_invested,
  SUM(i.token_amount) as total_tokens,
  (SUM(i.token_amount) / NULLIF(p.total_supply, 0) * 100) as ownership_percentage,
  COUNT(DISTINCT i.id) as investment_count,
  MAX(i.created_at) as last_investment_date,
  COALESCE(
    (SELECT SUM(amount_usd) FROM launchpad_revenues
     WHERE investor_address = i.wallet_address AND project_id = i.project_id),
    0
  ) as total_revenue_earned
FROM launchpad_investments i
JOIN launchpad_projects p ON i.project_id = p.id
WHERE i.status = 'completed'
GROUP BY i.wallet_address, i.project_id, p.name, p.token_symbol, p.total_supply;

-- =====================================================
-- 6. HELPER FUNCTIONS
-- =====================================================

-- Function to calculate investor's revenue share
CREATE OR REPLACE FUNCTION calculate_investor_revenue_share(
  p_project_id UUID,
  p_investor_address TEXT,
  p_total_revenue DECIMAL
)
RETURNS DECIMAL AS $$
DECLARE
  v_investor_tokens DECIMAL;
  v_total_supply DECIMAL;
  v_ownership_percentage DECIMAL;
  v_revenue_share DECIMAL;
BEGIN
  -- Get investor's total tokens
  SELECT COALESCE(SUM(token_amount), 0) INTO v_investor_tokens
  FROM launchpad_investments
  WHERE project_id = p_project_id
    AND wallet_address = LOWER(p_investor_address)
    AND status = 'completed';

  -- Get project's total supply
  SELECT total_supply INTO v_total_supply
  FROM launchpad_projects
  WHERE id = p_project_id;

  -- Calculate ownership percentage
  IF v_total_supply > 0 THEN
    v_ownership_percentage := (v_investor_tokens / v_total_supply);
  ELSE
    v_ownership_percentage := 0;
  END IF;

  -- Calculate revenue share
  v_revenue_share := p_total_revenue * v_ownership_percentage;

  RETURN v_revenue_share;
END;
$$ LANGUAGE plpgsql;

-- Function to distribute revenue to all investors
CREATE OR REPLACE FUNCTION distribute_project_revenue(
  p_project_id UUID,
  p_total_revenue DECIMAL,
  p_currency TEXT
)
RETURNS TABLE (
  investor_address TEXT,
  revenue_share DECIMAL,
  ownership_percentage DECIMAL
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    i.wallet_address,
    calculate_investor_revenue_share(p_project_id, i.wallet_address, p_total_revenue) as revenue_share,
    (SUM(i.token_amount) / NULLIF(p.total_supply, 0) * 100) as ownership_percentage
  FROM launchpad_investments i
  JOIN launchpad_projects p ON i.project_id = p.id
  WHERE i.project_id = p_project_id
    AND i.status = 'completed'
  GROUP BY i.wallet_address, p.total_supply
  HAVING SUM(i.token_amount) > 0;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- 7. TRIGGERS
-- =====================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_launchpad_investments_updated_at
  BEFORE UPDATE ON launchpad_investments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Auto-update project total_revenue when new revenue added
CREATE OR REPLACE FUNCTION update_project_total_revenue()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE launchpad_projects
  SET total_revenue = total_revenue + NEW.amount_usd
  WHERE id = NEW.project_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_project_revenue_on_distribution
  AFTER INSERT ON launchpad_revenues
  FOR EACH ROW
  EXECUTE FUNCTION update_project_total_revenue();

-- =====================================================
-- 8. SAMPLE DATA (FOR TESTING)
-- =====================================================

-- Uncomment to insert sample data for testing

/*
-- Sample project with owner wallet
UPDATE launchpad_projects
SET
  owner_wallet = '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
  total_supply = 1000000,
  token_price = 1.00
WHERE id = (SELECT id FROM launchpad_projects LIMIT 1);

-- Sample investment
INSERT INTO launchpad_investments (
  project_id,
  wallet_address,
  amount_usd,
  payment_method,
  token_amount,
  status,
  transaction_hash
) VALUES (
  (SELECT id FROM launchpad_projects LIMIT 1),
  '0x1234567890abcdef1234567890abcdef12345678',
  10000.00,
  'ETH',
  10000.00,
  'completed',
  '0xabc123...'
);

-- Sample revenue distribution
INSERT INTO launchpad_revenues (
  project_id,
  investor_address,
  amount_usd,
  distribution_currency,
  total_project_revenue,
  investor_token_amount,
  ownership_percentage,
  transaction_hash
) VALUES (
  (SELECT id FROM launchpad_projects LIMIT 1),
  '0x1234567890abcdef1234567890abcdef12345678',
  500.00,
  'ETH',
  50000.00,
  10000.00,
  1.00,
  '0xdef456...'
);
*/

-- =====================================================
-- SETUP COMPLETE
-- =====================================================

-- Verify tables were created
SELECT
  table_name,
  (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public'
  AND table_name IN (
    'launchpad_investments',
    'launchpad_revenues',
    'project_revenue_pool'
  )
ORDER BY table_name;
