-- =====================================================
-- INSERT 4 LAUNCHPAD PROJECTS
-- Run this in Supabase SQL Editor
-- =====================================================

-- Project 1: Embraer Phenom 300
INSERT INTO launchpad_projects (
  name,
  description,
  category,
  asset_type,
  location,
  year,
  image_url,
  cover_image_url,
  token_standard,
  token_symbol,
  token_price,
  total_supply,
  available_supply,
  target_amount,
  min_investment,
  max_investment,
  estimated_apy,
  revenue_model,
  target_waitlist,
  current_phase,
  status,
  current_waitlist,
  waitlist_target_days
) VALUES (
  'Embraer Phenom 300',
  'Fractional ownership of a 2021 Embraer Phenom 300 light jet based in Geneva. This aircraft offers exceptional performance for European routes with best-in-class cabin comfort. Perfect for business travelers seeking flexibility and luxury.',
  'private-jet',
  'Embraer Phenom 300',
  'Geneva, Switzerland',
  2021,
  'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=800',
  'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=1920',
  'ERC1400',
  'PHEN300',
  5000,
  2000,
  2000,
  10000000,
  5000,
  500000,
  14.5,
  'Charter Revenue',
  100,
  'waitlist',
  'active',
  25,
  90
) ON CONFLICT DO NOTHING;

-- Project 2: Gulfstream G550
INSERT INTO launchpad_projects (
  name,
  description,
  category,
  asset_type,
  location,
  year,
  image_url,
  cover_image_url,
  token_standard,
  token_symbol,
  token_price,
  total_supply,
  available_supply,
  target_amount,
  min_investment,
  max_investment,
  estimated_apy,
  revenue_model,
  target_waitlist,
  current_phase,
  status,
  current_waitlist,
  waitlist_target_days
) VALUES (
  'Gulfstream G550',
  'Ultra-long-range business jet with global reach. This 2019 Gulfstream G550 offers unmatched comfort and capability, serving routes from Dubai to the Americas and Asia. Ideal for high-net-worth individuals and corporations.',
  'private-jet',
  'Gulfstream G550',
  'Dubai, UAE',
  2019,
  'https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=800',
  'https://images.unsplash.com/photo-1474302770737-173ee21bab63?w=1920',
  'ERC1400',
  'G550-DXB',
  10000,
  6500,
  6500,
  65000000,
  10000,
  1000000,
  12.8,
  'Charter Revenue',
  150,
  'waitlist',
  'active',
  42,
  90
) ON CONFLICT DO NOTHING;

-- Project 3: Azimut 72 Yacht
INSERT INTO launchpad_projects (
  name,
  description,
  category,
  asset_type,
  location,
  year,
  image_url,
  cover_image_url,
  token_standard,
  token_symbol,
  token_price,
  total_supply,
  available_supply,
  target_amount,
  min_investment,
  max_investment,
  estimated_apy,
  revenue_model,
  target_waitlist,
  current_phase,
  status,
  current_waitlist,
  waitlist_target_days
) VALUES (
  'Mediterranean Yacht - Azimut 72',
  '72-foot luxury yacht based in Malta, perfect for Mediterranean charters. This stunning Azimut offers exceptional comfort and performance, with a proven charter track record generating consistent returns.',
  'yacht',
  'Azimut 72',
  'Malta',
  2022,
  'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800',
  'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=1920',
  'ERC1400',
  'AZI72-MLT',
  2500,
  600,
  600,
  1500000,
  2500,
  150000,
  16.2,
  'Charter Revenue',
  75,
  'waitlist',
  'active',
  18,
  90
) ON CONFLICT DO NOTHING;

-- Project 4: Ferrari F50
INSERT INTO launchpad_projects (
  name,
  description,
  category,
  asset_type,
  location,
  year,
  image_url,
  cover_image_url,
  token_standard,
  token_symbol,
  token_price,
  total_supply,
  available_supply,
  target_amount,
  min_investment,
  max_investment,
  estimated_apy,
  revenue_model,
  target_waitlist,
  current_phase,
  status,
  current_waitlist,
  waitlist_target_days
) VALUES (
  'Ferrari F50 - Ready to Buy',
  'Rare 1996 Ferrari F50 in pristine condition, ready for immediate purchase. One of only 349 units ever produced, this iconic supercar combines Formula 1 technology with road car usability. The vehicle is verified, serviced, and available for fractional ownership investment.',
  'luxury-car',
  'Ferrari F50',
  'Monaco',
  1996,
  'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800',
  'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1920',
  'ERC1400',
  'F50-MCO',
  10000,
  460,
  460,
  4600000,
  10000,
  500000,
  8.5,
  'Appreciation + Rental',
  50,
  'waitlist',
  'active',
  12,
  60
) ON CONFLICT DO NOTHING;

-- Verify insertion
SELECT name, category, status, current_waitlist, target_waitlist
FROM launchpad_projects
ORDER BY created_at DESC;
